### ISSUE TITLE
Sublime Text Key Mapping with Neovintageous

### ISSUE THREAD

**Issue by MichaelMFox** [gerardroche/gerardroche.github.io#2] opened 2020-05-30 00:00 UTC
Is this the right way to obtain ctrl-[ for escape (to command mode) for Neovintageous ?

{"keys": ["ctrl+["], "command": "_enter_normal_mode", "context":
            [
                { "key": "setting.command_mode", "operand": false },
                { "key": "setting.is_widget", "operand": false }
            ]
    },

**Comment by gerardroche** [comment] 2020-06-05 10:42
Duplicate of https://github.com/gerardroche/gerardroche.github.io/issues/3

**Closed by gerardroche** 2020-06-05 10:42 UTC
